var controls = ["<div class='plyr__controls'>",
    "<div class='plyr__progress'>",
        "<label for='seek{id}' class='plyr__sr-only'>Seek</label>",
        "<input id='seek{id}' class='plyr__progress--seek' type='range' min='0' max='100' step='0.5' value='0' data-plyr='seek'>",
        "<progress class='plyr__progress--played' max='100' value='0'>",
            "<span>0</span>% played",
        "</progress>",
        "<progress class='plyr__progress--buffer' max='100' value='0'>",
            "<span>0</span>% buffered",
        "</progress>",
    "</div>",
    "<span class='plyr__controls--left'>",
        "<button type='button' data-plyr='restart'>",
            "<svg><use xlink:href='#icon-restart'></use></svg>",
            "<span class='plyr__sr-only'>Restart</span>",
        "</button>",
        "<button type='button' data-plyr='rewind'>",
            "<svg><use xlink:href='#icon-rewind'></use></svg>",
            "<span class='plyr__sr-only'>Rewind {seektime} secs</span>",
        "</button>",
        "<button type='button' data-plyr='play'>",
            "<svg><use xlink:href='#icon-play'></use></svg>",
            "<span class='plyr__sr-only'>Play</span>",
        "</button>",
        "<button type='button' data-plyr='pause'>",
            "<svg><use xlink:href='#icon-pause'></use></svg>",
            "<span class='plyr__sr-only'>Pause</span>",
        "</button>",
        "<button type='button' data-plyr='fast-forward'>",
            "<svg><use xlink:href='#icon-fast-forward'></use></svg>",
            "<span class='plyr__sr-only'>Forward {seektime} secs</span>",
        "</button>",
        "<span class='plyr__time'>",
            "<span class='plyr__sr-only'>Current time</span>",
            "<span class='plyr__current-time'>00:00</span>",
        "</span>",
        "<span class='plyr__time'>",
            "<span class='plyr__sr-only'>Duration</span>",
            "<span class='plyr__duration'>00:00</span>",
        "</span>",
    "</span>",
    "<span class='plyr__controls--right'>",
        "<button type='button' data-plyr='mute'>",
            "<svg class='icon--muted'><use xlink:href='#icon-muted'></use></svg>",
            "<svg><use xlink:href='#icon-volume'></use></svg>",
            "<span class='plyr__sr-only'>Toggle Mute</span>",
        "</button>",
        "<label for='volume{id}' class='plyr__sr-only'>Volume</label>",
        "<input id='volume{id}' class='plyr__volume' type='range' min='0' max='10' value='5' data-plyr='volume'>",
        "<button type='button' data-plyr='captions'>",
            "<svg class='icon--captions-on'><use xlink:href='#icon-captions-on'></use></svg>",
            "<svg><use xlink:href='#icon-captions-off'></use></svg>",
            "<span class='plyr__sr-only'>Toggle Captions</span>",
        "</button>",
        "<button type='button' data-plyr='fullscreen'>",
            "<svg class='icon--exit-fullscreen'><use xlink:href='#icon-exit-fullscreen'></use></svg>",
            "<svg><use xlink:href='#icon-enter-fullscreen'></use></svg>",
            "<span class='plyr__sr-only'>Toggle Fullscreen</span>",
        "</button>",
    "</span>",
"</div>"].join("\n");

// Setup the player
plyr.setup('.js-media-player', {
	debug: 		true,
	title: 		'Video demo',
	tooltips: 	true,
	html: 		controls,
});
